In [1]:
import pandas

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)

In [2]:
X_train = dataframe.iloc[:, :8]
Y_train = dataframe.iloc[:, 8:]

In [3]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, Y_train)

/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/homebrew/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [50]:
import numpy as np

# sample = np.array([23, 12, 64, 34, 0, 22, 0.65, 34]).reshape(-1, 1)
sample = [[23, 12, 60, 34, 0, 22, 0.65, 34]]
model.predict(sample)

/opt/homebrew/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [55]:
!pip3 install pickle-mixin

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Preparing metadata (setup.py) ... done
  Created wheel for pickle-mixin: filename=pickle_mixin-1.0.2-py3-none-any.whl size=6008 sha256=c33d25560606aa16859afcb3b1a1be88fdd8bd95bcdf4f2dac4ae9aefe2a36dd
  Stored in directory: /Users/andrewwolf/Library/Caches/pip/wheels/58/c6/8b/061bd4edc8cea2b2235758c3e50473d08499236fbfdd21e6b3
Successfully built pickle-mixin
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command

In [67]:
import pickle

filename = 'models/logit.sav'
pickle.dump(model, open(filename, 'wb'))

In [68]:
!ls

Dockerfile         model.ipynb        reset.sh           stop.sh
api.py             models             restart.sh
docker-compose.yml openapi            src
logit_model.sav    requirements.txt   start.sh


In [69]:
filename = 'models/logit.sav'

loaded_model = pickle.load(open(filename, 'rb'))

In [73]:
sample = [[23, 12, 64, 34, 0, 22, 0.65, 34]]

In [74]:
loaded_model.predict(sample)

/opt/homebrew/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [14]:
from sklearn.svm import SVC

model = SVC(probability=True)
model.fit(X_train, Y_train)

/opt/homebrew/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(probability=True)

In [15]:
model.coef_

AttributeError: coef_ is only available when using a linear kernel

In [16]:
import numpy as np

# sample = np.array([23, 12, 64, 34, 0, 22, 0.65, 34]).reshape(-1, 1)
sample = [[23, 12, 60, 34, 0, 22, 0.65, 34]]
model.predict(sample)

/opt/homebrew/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [17]:
import pickle
filename='models/svm.sav'

pickle.dump(model, open(filename, 'wb'))